--- # Jekyll config file
# vim: nospell
# Site settings
port: 4000
lang: en
title: Dr. Michel Combes's Resume
description: Directeur Ingéniérie
favicon: /assets/img/favicon.png
photo: /assets/img/michel-circ1.png
#pdf: DrMichelCombes-CV.pdf
baseurl: ''
url: https://mcombes.resumesm.gq/
rss_url: /pages/atom.xml
google_analytics: UA-146588632-1
search: https://duckduckgo.com/?q

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  fullname: Dr. Michel G. Combes
  name: Michel Combes (PhD)
  title:
    fr: "Ingénieur Polymathique avec expérience"
    en: "Senior Polymathic Engineer"
  address: Ecublens, VD, Suisse
  phone: "+41 7676 0 9400"
  email: mgcombes@gmail.com
  link: http://linkedin.com/in/michel-combes
  weibo:
  github: michel47
  linkedin: mgc04
  linkedin: michel-combes
  telegram: cryptomgc
  twitter: mgcombes
  gavatar: /resumecard/assets/img/favicon.png
  stackoverflow:
